# Generated by Django 4.1.7 on 2023-03-05 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65536)),
                ('authors', models.CharField(max_length=65536)),
                ('year', models.IntegerField()),
                ('date', models.CharField(max_length=65536)),
                ('url', models.CharField(max_length=65536)),
                ('citation', models.CharField(max_length=65536)),
                ('keywords', models.CharField(max_length=65536)),
                ('tags', models.CharField(max_length=65536)),
                ('abstract', models.CharField(max_length=65536)),
                ('ai_abstract', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=65536)),
                ('source', models.IntegerField()),
                ('keywords', models.CharField(max_length=65536)),
                ('paraphrased', models.IntegerField()),
                ('location', models.CharField(max_length=65536)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='j2a.article')),
            ],
        ),
    ]
